
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ID IF LBRACE LPAREN NUM OPTR RBRACE RPAREN SEMICOLON WHILEstmt : ID ASSIGN expr SEMICOLONstmt : LBRACE stmtlist RBRACEstmt : IF LPAREN expr RPAREN stmtstmt : WHILE LPAREN expr RPAREN stmtstmtlist : stmtstmtlist : stmtlist stmtexpr : IDexpr : NUMexpr : expr OPTR expr'
    
_lr_action_items = {'ID':([0,3,6,7,8,9,10,14,15,18,19,20,21,23,24,],[2,2,11,2,-5,11,11,-2,-6,-1,11,2,2,-3,-4,]),'LBRACE':([0,3,7,8,14,15,18,20,21,23,24,],[3,3,3,-5,-2,-6,-1,3,3,-3,-4,]),'IF':([0,3,7,8,14,15,18,20,21,23,24,],[4,4,4,-5,-2,-6,-1,4,4,-3,-4,]),'WHILE':([0,3,7,8,14,15,18,20,21,23,24,],[5,5,5,-5,-2,-6,-1,5,5,-3,-4,]),'$end':([1,14,18,23,24,],[0,-2,-1,-3,-4,]),'ASSIGN':([2,],[6,]),'LPAREN':([4,5,],[9,10,]),'NUM':([6,9,10,19,],[13,13,13,13,]),'RBRACE':([7,8,14,15,18,23,24,],[14,-5,-2,-6,-1,-3,-4,]),'SEMICOLON':([11,12,13,22,],[-7,18,-8,-9,]),'OPTR':([11,12,13,16,17,22,],[-7,19,-8,19,19,19,]),'RPAREN':([11,13,16,17,22,],[-7,-8,20,21,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt':([0,3,7,20,21,],[1,8,15,23,24,]),'stmtlist':([3,],[7,]),'expr':([6,9,10,19,],[12,16,17,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stmt","S'",1,None,None,None),
  ('stmt -> ID ASSIGN expr SEMICOLON','stmt',4,'p_stmt_assign','MiniCParser.py',14),
  ('stmt -> LBRACE stmtlist RBRACE','stmt',3,'p_stmt_block','MiniCParser.py',19),
  ('stmt -> IF LPAREN expr RPAREN stmt','stmt',5,'p_stmt_if','MiniCParser.py',25),
  ('stmt -> WHILE LPAREN expr RPAREN stmt','stmt',5,'p_stmt_while','MiniCParser.py',30),
  ('stmtlist -> stmt','stmtlist',1,'p_stmtlist_single','MiniCParser.py',37),
  ('stmtlist -> stmtlist stmt','stmtlist',2,'p_stmtlist_multiple','MiniCParser.py',42),
  ('expr -> ID','expr',1,'p_expr_id','MiniCParser.py',49),
  ('expr -> NUM','expr',1,'p_expr_num','MiniCParser.py',54),
  ('expr -> expr OPTR expr','expr',3,'p_expr_optr','MiniCParser.py',59),
]
